### ISSUE TITLE
Pg crash on call to set_config_option()

### ISSUE THREAD

**Issue by darold** [rjuju/pg_anonymize#11]
The problem occurs when playing the regression test using `make installcheck` on PG16.
```
Program received signal SIGSEGV, Segmentation fault.
__strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
77	../sysdeps/x86_64/multiarch/strlen-evex.S: Aucun fichier ou dossier de ce nom.
(gdb) bt
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00005acdf7c682ce in guc_strdup ()
#2  0x00005acdf7c7bf0b in ?? ()
#3  0x00005acdf7c7cb36 in set_config_option_ext ()
#4  0x00005acdf7c7e02d in set_config_option ()
#5  0x0000718332cbde30 in pgan_check_expression_valid (rel=0x7183259f0818, object=0x7fff55aae180, 
    seclabel=0x5acdf808efc0 "error") at pg_anonymize.c:352
#6  0x0000718332cbc899 in pgan_object_relabel (object=0x7fff55aae180, seclabel=0x5acdf808efc0 "error")
    at pg_anonymize.c:1127
```
The reason is a call to pstrdup() in a PG_TRY() section and use of the assigned variable in the PG_CATCH() section, a PR is coming.

**Comment by rjuju** [comment]
Thanks a lot for the bug report and bugfix!
